# Setup
title:               Embedded Journey
tagline:             'Blog'
description:         'Blog about embedded software development, embedded Linux, QEMU, Qt and other stuff.'
url:                 https://straxy.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Strahinja Jankovic
  url:               https://straxy.blogspot.com
  email:             strahinja.p.jankovic@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
#google_analytics_id: UA-146052-15
